MCS-433 Integration Test 4.0 Updates and Autofixer
NextCenturyCorporation/MCS pull request #275
Opened 2021-03-23 14:46 UTC by ThomasSchellenbergNextCentury

- Updated the integration tests for the performer agent's new height (in the 4.0 release)
- Added an autofixer feature to the integration tests

Please take a look at the README, integration_test_utils, and run_handmade_tests scripts for new code.

2021-03-23 15:44 UTC, kdrumm approved these changes
Looks good to me

2021-03-23 16:26 UTC, deanwetherby approved these changes

2021-03-23 17:39 UTC, brianpippin approved these changes

2021-03-24 11:12 UTC, kdrumm requested changes
Running run_tests.py will error because it is missing the autofix variable.  We need to either pass it or give autofix a default value.

2021-03-24 14:01 UTC, ThomasSchellenbergNextCentury commented
@kdrumm Doh! Nice catch. Will fix. Thanks!

2021-03-24 18:26 UTC, merged