Configurable reward and penalty scores
NextCenturyCorporation/MCS pull request #480
Opened 2022-01-26 14:44 UTC by jaudick

Right now the goal reward can be a float but before this change it was an int. How do we feel about it being a float if configured that way?

2022-01-28 02:00 UTC, ThomasSchellenbergNextCentury commented on docs/source/install.rst
> +Changes the postive reward recieved for achieving a goal.
Would be good for these three options to list their respective defaults.

2022-01-28 02:06 UTC, ThomasSchellenbergNextCentury commented on tests/test_reward.py
> +            obj['position'] = {'x': 0.5, 'y': 0.0 + i, 'z': 0.5}
FYI In the future you may find it easier to do something like this:

```python
obj = {
    "objectId": str(i),
    "objectBounds": {
        "objectBoundsCorners": [
            {'x': 0.0, 'y': 0.0 + i, 'z': 0.0},
            {'x': 0.0, 'y': 0.0 + i, 'z': 0.0},
            {'x': 1.0, 'y': 0.0 + i, 'z': 0.0},
            {'x': 1.0, 'y': 0.0 + i, 'z': 1.0},
            {'x': 0.0, 'y': 0.0 + i, 'z': 1.0},
            {'x': 0.0, 'y': 1.0 + i, 'z': 0.0},
            {'x': 1.0, 'y': 1.0 + i, 'z': 0.0},
            {'x': 1.0, 'y': 1.0 + i, 'z': 1.0},
            {'x': 0.0, 'y': 1.0 + i, 'z': 1.0}
        ]
    },
    "position": {'x': 0.5, 'y': 0.0 + i, 'z': 0.5}
}
```

2022-01-28 02:07 UTC, ThomasSchellenbergNextCentury requested changes
I'm getting a bunch of unit test errors. They're all `TypeError: float() argument must be a string or a number, not 'NoneType'`. Is it just me?

2022-01-28 14:45 UTC, jaudick commented
> I'm getting a bunch of unit test errors. They're all `TypeError: float() argument must be a string or a number, not 'NoneType'`. Is it just me?

Not just you, looks like I missed that configs were being set in this test file. I had only tested the reward unit tests. I will get on this

2022-01-28 15:13 UTC, jaudick commented
@ThomasSchellenbergNextCentury the error is fixed

2022-01-28 15:54 UTC, deanwetherby reviewed
Some unit tests specifically for the score adjustment function would be good to add to this PR. There are numerous conditions to test for including penalty values of None and if the task has already been completed successfully.

2022-01-28 16:34 UTC, jaudick commented
> There are numerous conditions to test for including penalty values of None
@deanwetherby This is confusing me a little. Are you saying that None would be passed in intentionally to have penalty values of zero?

> and if the task has already been completed successfully.
Also confused here. Are you asking to test multiple values of goal_reward configs like: test 500, test 1.5, test 0.1? or test if penalties happen after the goal is achieved?

2022-01-28 16:53 UTC, deanwetherby commented
> @deanwetherby This is confusing me a little. Are you saying that None would be passed in intentionally to have penalty values of zero?
> 
> Are you asking to test multiple values of goal_reward configs like: test 500, test 1.5, test 0.1? or test if penalties happen after the goal is achieved?

You'll want to check each branching condition in the function. What do you expect to happen if step_penalty or lava_penalty is None? What if the current_score is 1 vs not 1? etc. The adjusted score output is going to vary on those conditions.

Unit tests are also a form of documentation so another developer can see how the function gets used and what to expect for an output.

```
        step_penalty = STEP_PENALTY if step_penalty is None else step_penalty
        lava_penalty = LAVA_PENALTY if lava_penalty is None else lava_penalty
        if current_score == 1:
            return current_score - ((number_steps - 1) * float(step_penalty))

        if steps_on_lava is None:
            steps_on_lava = 0
```

2022-01-31 15:57 UTC, jaudick commented
@deanwetherby I added three additional unit tests based on your suggestions

2022-01-31 16:04 UTC, deanwetherby approved these changes

2022-01-31 17:12 UTC, ThomasSchellenbergNextCentury approved these changes

2022-01-31 19:28 UTC, brianpippin approved these changes

2022-01-31 20:47 UTC, merged