Mcs 1528 toggle metadata mcs config
NextCenturyCorporation/MCS pull request #639
Opened 2022-12-24 01:19 UTC by phile-caci

Added two config settings on the MCS config to toggle disable_object_list and disable_position.  They can only be disabled at oracle metadata level.  At level1,2  and none, they are always disabled.  (Hopefully I have that correct).

2022-12-28 16:00 UTC, brianpippin commented
The code looks good so far but I feel like we need additional configs.  I think is_depth_maps_enabled and is_object_masks_enabled needs an over ride config potential as well, so they could toggle one of them on or off, right now they both are returned and some teams might only want one.   Looking to see if there are other configs potentially missed.

2023-01-04 16:29 UTC, rartiss55 commented
Left some comments, overall I think this makes sense + tested things out with some of the depth/object mask fields at different levels.

2023-01-04 19:15 UTC, rartiss55 requested changes

2023-01-05 13:55 UTC, phile-caci commented on tests/test_parameter.py
>              "action": "TestAction",
Hi @rartiss55 ,

I think they're there already:

105            "renderDepthImage": False,
106            "renderObjectImage": False,

Let me know if that's not what you meant.
Thanks!

2023-01-05 14:38 UTC, rartiss55 commented on tests/test_parameter.py
>              "action": "TestAction",
Whoops, they were hidden in the diff, I see them now, thanks!

2023-01-05 14:44 UTC, phile-caci commented on machine_common_sense/parameter.py
> +            consistentColors=consistent_colors,
Should be here too (hidden in the diff like you mentioned already):

111            renderDepthImage=self.config.is_depth_maps_enabled(),
112            renderObjectImage=self.config.is_object_masks_enabled(),

2023-01-05 14:45 UTC, phile-caci commented on docs/source/install.rst
> +If `true`, will generate depth maps. Metadata Tier will override `enable_depth_maps`. Will only generate dept maps for Metadata tier [level1, level2, oracle]. Default: true
Corrected, thanks!

2023-01-05 14:45 UTC, phile-caci commented on sample_config.ini
> +#Creates object masks in output. Will only generate object masks for Metadata tier [level2, oracle]. Default: true1
Corrected, thanks!

2023-01-05 18:10 UTC, ThomasSchellenbergNextCentury requested changes
@phile-caci @brianpippin When `disable_object_list` is `true` (including at non-oracle metadata levels, since it's `true` by default there), the performer can never achieve a positive reward, since the reward calculation requires the object list (in `controller_output_handler.py`, see `_get_step_metadata`, where it calls `calculate_reward`). This doesn't seem like it would work, since you'd never be able to succeed in any retrieval scenes.

2023-01-05 18:44 UTC, ThomasSchellenbergNextCentury commented
> > @phile-caci @brianpippin When `disable_object_list` is `true` (including at non-oracle metadata levels, since it's `true` by default there), the performer can never achieve a positive reward, since the reward calculation requires the object list (in `controller_output_handler.py`, see `_get_step_metadata`, where it calls `calculate_reward`). This doesn't seem like it would work, since you'd never be able to succeed in any retrieval scenes.
> 
> If that is the case perhaps this should be named to only_return_goal_object and that is the only object returned if we think this will improve performance at training time.

That seems reasonable to me. Even at non-oracle metadata levels, we still use the target object's output metadata within the MCS code for the reward calculation, even though we don't pass it back to the TA1 systems via the StepMetadata. I _believe_ this is the only place where we would need it. Unfortunately, this means that the MCS python code will need to pass information about all the target objects (probably their object IDs) to the Unity code (probably in `wrap_step`), so Unity knows which objects to process and which objects to skip. Shouldn't be too hard -- just another thing to do.

2023-01-05 21:50 UTC, ThomasSchellenbergNextCentury commented on machine_common_sense/config_manager.py
> +    CONFIG_DISABLE_POSITION = 'disable_position'
In addition to your unit tests, it might be a good idea to add a few new integration tests for the `disable_position` and `disable_object_list` (or its replacement, as Brian and I have discussed) properties. You can write specific `config.ini` files for specific integration tests in order to test these properties -- see integration test 119 for examples. Given the hiccup with the rewards, we should have integration tests for both a normal "retrieval" scene (like test 073, though we use a soccer ball instead of a trophy these days) and a "multi retrieval" scene (like test 175).

2023-01-11 21:50 UTC, rartiss55 approved these changes

2023-01-11 21:54 UTC, rartiss55 commented
I know Thomas had some additional concerns, but  just wanted to confirm my previous comments were addressed :)

2023-01-13 01:14 UTC, phile-caci commented
@ThomasSchellenbergNextCentury,  I didn't get too deep on the integration testing.  Just making sure we're good with the approach first.  

Replaced `disable_object_list` with `only_return_goal_object`. At oracle level will only return the goal objects.
Thanks!

2023-01-13 15:50 UTC, ThomasSchellenbergNextCentury commented on integration_tests/config_oracle.ini
> +only_return_goal_object = true
We don't want to keep this here, right? Since it would affect ALL the integration tests?

2023-01-13 15:58 UTC, ThomasSchellenbergNextCentury commented on integration_tests/data/182.multiple_targets_config_only_goal_objs.level2_only_goal_objects.outputs.json
> +  }
I know you're not done with your integration tests yet, but I wanted to note that you'll need `"objects_count": X` here (where X is the number of target objects) in your `outputs.json` file for testing `only_return_goal_object = true`. This will ensure there are no extraneous objects being returned in the step metadata.

For some more detail: The integration tests don't do a 1-for-1 comparison of the `"objects"` in the `outputs` file and the objects in the step metadata. Instead, they iterate over the `"objects"` in the `outputs` file, find the corresponding object in the step metadata, and run the listed checks for that object. This is so you can have a scene with a bunch of objects in it, but maybe you only care about checking a subset of them. The same is true for the `structural_objects` (and `structural_objects_count`).

2023-01-13 16:00 UTC, ThomasSchellenbergNextCentury commented on docs/source/install.rst
> +If `true`, will generate object masks. Metadata Tier will override `enable_depth_maps`. Will only generate object masks for Metadata tier [level2, oracle]. Default: true
It's not super important, but would these options be better as "disable_depth_maps" and "disable_object_masks"? Maybe it's just me, but I tend to think of config options as "off" by default, and you set them to turn them "on", but these are currently the reverse.

2023-01-13 16:02 UTC, ThomasSchellenbergNextCentury commented
@phile-caci This looks much better, though I'd appreciate having a few good integration tests before signing off (I know you said you're planning to work on them). Let me know if you'd like any help with them.

2023-01-13 16:41 UTC, phile-caci commented on integration_tests/config_oracle.ini
> +only_return_goal_object = true
I did rerun all of the integration test at oracle and they looked like they all passed, but agree probably shouldn't keep this here.  There's doesn't seem to be a built in mechanism now to handle a config parameter?  I can add another argument to accept config parameters and values if that makes sense?

2023-01-13 16:49 UTC, ThomasSchellenbergNextCentury commented on integration_tests/config_oracle.ini
> +only_return_goal_object = true
Hmm, I'm definitely seeing errors at the oracle metadata level (for example, test 005 is failing on step 0 with "objects_count: 0 != 1").

You can create a config file for a specific test, naming it `<test_name>.<metadata_level>.config.ini` and putting it in the `integration_tests/data/` folder. See test 119 for an example.

2023-01-13 16:52 UTC, phile-caci commented on integration_tests/config_oracle.ini
> +only_return_goal_object = true
Ah.. thanks!

2023-01-13 16:57 UTC, phile-caci commented on docs/source/install.rst
> +If `true`, will generate object masks. Metadata Tier will override `enable_depth_maps`. Will only generate object masks for Metadata tier [level2, oracle]. Default: true
I can make the change if you like, I only went that route because it looked like the code was mostly setup for it being enabled by default.

2023-01-13 17:00 UTC, ThomasSchellenbergNextCentury commented on docs/source/install.rst
> +If `true`, will generate object masks. Metadata Tier will override `enable_depth_maps`. Will only generate object masks for Metadata tier [level2, oracle]. Default: true
I didn't mean for you to change the existing code. I just meant that the options could be "disable_whatever", and "false" by default, which would mean they're actually enabled by default. Just a semantics thing.

2023-01-13 18:14 UTC, phile-caci commented on docs/source/install.rst
> +If `true`, will generate object masks. Metadata Tier will override `enable_depth_maps`. Will only generate object masks for Metadata tier [level2, oracle]. Default: true
Ahh got it. I'll make the change

2023-01-13 21:56 UTC, phile-caci commented
@ThomasSchellenbergNextCentury , 

I think I hit all the updates, let me know if I missed anything, thanks!

2023-01-16 15:01 UTC, ThomasSchellenbergNextCentury reviewed
It would be nice if the new integration test for `only_return_goal_object: true` actually had the targets being picked up, and verified that the "reward" changes, but I won't let that hold up my approval, since I know were' on a deadline.

2023-01-16 16:22 UTC, phile-caci commented
> It would be nice if the new integration test for `only_return_goal_object: true` actually had the targets being picked up, and verified that the "reward" changes, but I won't let that hold up my approval, since I know were' on a deadline.

Added `only_return_goal_object` true integration test.  There are 12 objects in the scene, only 4 are goal target objects.  At oracle level, should only return 4 objects.

2023-01-16 16:51 UTC, ThomasSchellenbergNextCentury commented
I've run this through twice now, and I keep getting an error on integration test 171:

```
    171.triggered_by_correct_sequence (oracle): Step 37 failed:
        objects chest_2 visible: False != True
```

This only happens if I run the entire test suite (not the specific test).

If no one else is seeing this, then maybe something is funky with my local build. I don't want it to hold up approval. (And I suppose Jenkins will let us know if the tests fail after merging.)

2023-01-16 16:53 UTC, ThomasSchellenbergNextCentury commented on integration_tests/data/186.only_return_goal_objects_true.actions.txt
> +MoveAhead
@phile-caci I think you misunderstood my comment. I meant the test should involve walking around and picking up all of the soccer balls, and checking the "reward" in the "*.outputs.json" files.

Giving the timing, I'm fine if we just want to handle this in a separate ticket.

2023-01-16 17:02 UTC, phile-caci commented on integration_tests/data/186.only_return_goal_objects_true.actions.txt
> +MoveAhead
Ugh.. sry.. I'll go ahead and create the ticket.

2023-01-16 17:31 UTC, phile-caci commented
> I've run this through twice now, and I keep getting an error on integration test 171:
> 
> ```
>     171.triggered_by_correct_sequence (oracle): Step 37 failed:
>         objects chest_2 visible: False != True
> ```
> 
> This only happens if I run the entire test suite (not the specific test).
> 
> If no one else is seeing this, then maybe something is funky with my local build. I don't want it to hold up approval. (And I suppose Jenkins will let us know if the tests fail after merging.)

I ran the entire suite, I didn't get an error on 171 but I did get an error with `run_depth_and_segmentation_test`, but it looks more like an approx issue:

```
FAILED INTEGRATION TESTS:
    run_depth_and_segmentation_test (level1): Step 0 level1 failed: depth_map_list[0][339][376] value of 1.0898563861846924 is not close enough to expected value of 1.0899707078933716
    run_depth_and_segmentation_test (level2): Step 0 level2 failed: depth_map_list[0][339][376] value of 1.0898563861846924 is not close enough to expected value of 1.0899707078933716
    run_depth_and_segmentation_test (oracle): Step 0 oracle failed: depth_map_list[0][339][376] value of 1.0898563861846924 is not close enough to expected value of 1.0899707078933716
```

2023-01-16 19:08 UTC, merged