MCS 1650 - Added "only_return_goal_object" integration tests
NextCenturyCorporation/MCS pull request #653
Opened 2023-04-04 12:48 UTC by NDCACI

Single-retrieval goal. Used test 109 to make test 189.

Intuitive physics scene. Used test 150 to make test 190.

Imitation scene. Used test 176 to make test 191.

Normal “passive” scene. Used test 69 to make test 192.

2023-04-07 15:15 UTC, ThomasSchellenbergNextCentury commented on integration_tests/data/192.intuitive_physics_only_return_goal_object.scene.json
> +    }
I'm getting an error if there isn't a `metadata` property defined in the `goal`. You can change it to something like this:

```json
"goal": {
    "category": "passive",
    "metadata": {}
}
```

2023-04-07 15:18 UTC, ThomasSchellenbergNextCentury commented on integration_tests/data/189.single-retrieval_only_return_goal_object.scene.json
> +    "name": "soccer ball can be picked up and will roll an expected distance",
You should update the `name` property in each of these scene files to be more descriptive for the new tests. For example, this `name` could be something like "only return goal object in single retrieval scene"

2023-04-07 15:20 UTC, ThomasSchellenbergNextCentury commented on integration_tests/data/190.intuitive_only_return_goal_object.scene.json
> +    "objects": [
I'm realizing for this test (190), and test 192, we should probably include a non-structural object in the scene too. You can just copy the `soccer_ball` from test 189 and add it to the `objects` list here -- I think that will work fine.

2023-04-07 15:22 UTC, ThomasSchellenbergNextCentury commented
There's also a note at the bottom of the ticket description to update either test 182 or 186 (not both) to pick up all of the soccer balls.

2023-04-19 18:42 UTC, ThomasSchellenbergNextCentury requested changes
1. I was still getting an error when trying to run test 192. I think we weren't handling an empty metadata dict correctly. I pushed a fix for the issue to this branch (hope you don't mind).
2. The names of the files for test 192 still have "intuitive_physics" in them; it should be replaced with "passive".
3. I'm seeing errors for tests 190 and 192 at oracle metadata level. You can run the integration tests with the `--dev --autofix` flags to update the values automatically (I'm assuming they just haven't been updated yet due to your most recent changes).

2023-04-19 19:04 UTC, ThomasSchellenbergNextCentury commented on integration_tests/data/186.only_return_goal_objects_true.actions.txt
> +DropObject,objectId=460d9b68-63ca-433c-8b7d-84ae1d50c1ee
This test (186) also wasn't working for me. I think you need to expand the 3 `outputs.json` files for test 186 to account for the newly added steps. (The lists in each of those files should contain one element per step, plus one for initialization; so, for this test with 9 steps, the lists should contain 10 elements.)

2023-05-10 17:20 UTC, NDCACI commented on integration_tests/data/186.only_return_goal_objects_true.actions.txt
> +DropObject,objectId=460d9b68-63ca-433c-8b7d-84ae1d50c1ee
I went through all your comments and I think this is good for review again

2023-05-12 19:09 UTC, phile-caci approved these changes
Looks good to me.  No issues running the updated integration tests.

2023-05-13 02:08 UTC, merged