MCS-1726 - added timeout
NextCenturyCorporation/MCS pull request #654
Opened 2023-04-07 13:57 UTC by NDCACI

First pass, seemed too simple so I feel like I missed something. No test added yet.

2023-04-08 02:18 UTC, ThomasSchellenbergNextCentury requested changes
Oof, OK. My fault, for not realizing there are actually two different timeouts in the code:
- A timeout for each action step, which is set by CONFIG_TIMEOUT, which you've modified here (see `_check_for_step_timeout` in `controller.py`)
- A timeout for initializing the controller, which was the one we wanted to be able to set for this ticket (see `TIME_LIMIT_SECONDS` and `get_controller_with_timeout` in `__init__.py`)

I'm thinking it's important to keep these settings separate (at least for now), so, in order to focus on the second timeout, if you could please:
1. Add a new config setting to `config_manager.py` (maybe `CONFIG_CONTROLLER_TIMEOUT = 'controller_timeout'` ?), with a corresponding getter (you can use `180` as the default value)
2. In `__init__.py`, in `get_controller_with_timeout`, use the configured "controller_timeout" instead of TIME_LIMIT_SECONDS
3. Add new unit tests
4. Add a new section for the "controller_timeout" to “Config File Properties” in `docs/source/install.rst`

You knew this was too easy! :)

2023-04-18 13:54 UTC, ThomasSchellenbergNextCentury commented on machine_common_sense/__init__.py
> +            controller = future.result(timeout=config.get_controller_timeout)
You should remove the TIME_LIMIT_SECONDS variable.

2023-04-18 13:59 UTC, ThomasSchellenbergNextCentury commented on machine_common_sense/__init__.py
> +            controller = future.result(timeout=config.get_controller_timeout)
Need parentheses after the function call (`config.get_controller_timeout()`)

2023-04-18 16:55 UTC, ThomasSchellenbergNextCentury approved these changes
Looks great!

2023-04-21 15:23 UTC, jaudick approved these changes

2023-04-21 15:29 UTC, brianpippin approved these changes

2023-05-13 02:09 UTC, merged