MCS-1442 a few updates to unit tests after get component call changes
NextCenturyCorporation/MCS pull request #659
Opened 2023-05-05 18:24 UTC by jaudick

2023-05-10 12:42 UTC, ThomasSchellenbergNextCentury commented on integration_tests/data/171.triggered_by_correct_sequence.actions.txt
> +PickupObject,objectId=target_1
Was this necessary as part of the GetComponent changes? Or just some cleanup that got included here?

2023-05-10 14:00 UTC, jaudick commented on integration_tests/data/171.triggered_by_correct_sequence.actions.txt
> +PickupObject,objectId=target_1
Ah so I moved the performer start because on edge frames when going from left to right the middle chest was returning that it was not visible when it should have been. So I moved the performer forward a little bit and that fixed it. I felt it was ok to do that quick fix because this happened on the two frames where the middle chest was way off on the edge with a few visible pixels. When I was messing around with performer distances I just changed it to objectId so I could make sure I was picking it up. I can change it back now to image coords because I have a performer start that works consistently.

2023-05-10 19:29 UTC, ThomasSchellenbergNextCentury commented
@jaudick I got test errors on 159 and 163. It appears that _some_ of the changes you made work for me, but some do not. Very weird.

Fortunately, the integration tests have a built-in work-around: In the "output.json" files, you can specify a range for numerical variables, as a list of `[min, max]`, like this: `"direction_z": [0.35, 0.38]`. You have to do this manually, and try not to abuse it, but it's useful for these scenarios where the Unity RNG is a little off for these strange scenarios. For rotations, the integration tests always do a `% 360` on them, so you can specify the range like this: `"rotation_y": [359, 360]`. Let me know if you have any trouble with this.

Here are the errors I got:

```
RUNNING SCENE: 159.open_close_on_openable_object_order_of_return_status.scene.json
Step 0 failed:
        objects small_ball direction_z: 0.35535067319869995 != 0.38
        objects small_ball distance: 0.7363455295562744 != 0.72
RUNNING SCENE: 160.put_into_not_receptacles.scene.json
RUNNING SCENE: 161.obstructed_in_distance_always_not_visible.scene.json
RUNNING SCENE: 162.obstructed_put_in_receptacle.scene.json
RUNNING SCENE: 163.all_actions_on_room_walls_and_floor.scene.json
Step 0 failed:
        objects ball direction_x: 0.2655588388442993 != 0.3
        objects ball direction_y: -0.9477002024650574 != -0.93
        objects ball direction_z: 0.17703908681869507 != 0.2
        objects ball position_x: 0.1881667673587799 != 0.21
Step 1 failed:
        objects ball distance: 0.7499520778656006 != 0.73
        objects ball rotation_y: 359 != 0
Step 2 failed:
        objects ball rotation_y: 359 != 0
Step 3 failed:
        objects ball rotation_y: 359 != 0
Step 4 failed:
        objects ball rotation_y: 359 != 0
Step 5 failed:
        objects ball rotation_y: 359 != 0
Step 6 failed:
        objects ball rotation_y: 359 != 0
Step 7 failed:
        objects ball rotation_y: 359 != 0
Step 8 failed:
        objects ball rotation_y: 359 != 0
Step 9 failed:
        objects ball rotation_y: 359 != 0
Step 10 failed:
        objects ball rotation_y: 359 != 0
Step 11 failed:
        objects ball rotation_y: 359 != 0
Step 12 failed:
        objects ball rotation_y: 359 != 0
Step 13 failed:
        objects ball rotation_y: 359 != 0
Step 14 failed:
        objects ball rotation_y: 359 != 0
Step 15 failed:
        objects ball rotation_y: 359 != 0
Step 16 failed:
        objects ball rotation_y: 359 != 0
Step 17 failed:
        objects ball rotation_y: 359 != 0
Step 18 failed:
        objects ball rotation_y: 359 != 0
Step 19 failed:
        objects ball rotation_y: 359 != 0
Step 20 failed:
        objects ball rotation_y: 359 != 0
Step 21 failed:
        objects ball rotation_y: 359 != 0
Step 22 failed:
        objects ball rotation_y: 359 != 0
Step 23 failed:
        objects ball rotation_y: 359 != 0
Step 24 failed:
        objects ball rotation_y: 359 != 0
Step 25 failed:
        objects ball rotation_y: 359 != 0
Step 26 failed:
        objects ball rotation_y: 359 != 0
Step 27 failed:
        objects ball rotation_y: 359 != 0
Step 28 failed:
        objects ball rotation_y: 359 != 0
Step 29 failed:
        objects ball rotation_y: 359 != 0
Step 30 failed:
        objects ball rotation_y: 359 != 0
Step 31 failed:
        objects ball rotation_y: 359 != 0
Step 32 failed:
        objects ball rotation_y: 359 != 0
Step 33 failed:
        objects ball rotation_y: 359 != 0
Step 34 failed:
        objects ball rotation_y: 359 != 0
Step 35 failed:
        objects ball rotation_y: 359 != 0
Step 36 failed:
        objects ball rotation_y: 359 != 0
Step 37 failed:
        objects ball rotation_y: 359 != 0
Step 38 failed:
        objects ball rotation_y: 359 != 0
Step 39 failed:
        objects ball rotation_y: 359 != 0
Step 40 failed:
        objects ball rotation_y: 359 != 0
Step 41 failed:
        objects ball rotation_y: 359 != 0
Step 42 failed:
        objects ball rotation_y: 359 != 0
Step 43 failed:
        objects ball rotation_y: 359 != 0
Step 44 failed:
        objects ball rotation_y: 359 != 0
Step 45 failed:
        objects ball rotation_y: 359 != 0
Step 46 failed:
        objects ball rotation_y: 359 != 0
Step 47 failed:
        objects ball rotation_y: 359 != 0
Step 48 failed:
        objects ball rotation_y: 359 != 0
Step 49 failed:
        objects ball rotation_y: 359 != 0
Step 50 failed:
        objects ball rotation_y: 359 != 0
```

2023-05-10 19:42 UTC, ThomasSchellenbergNextCentury approved these changes
Ignore my previous (now deleted) comment about some tests not working; everything is passing for me.

2023-05-15 15:05 UTC, phile-caci requested changes
No issue on code changes

I was getting an intermittent error for test 171.

```
    run_depth_and_segmentation_test (level1): Step 0 level1 failed: depth_map_list[0][339][376] value of 1.0898563861846924 is not close enough to expected value of 1.0899707078933716
    run_depth_and_segmentation_test (level2): Step 0 level2 failed: depth_map_list[0][339][376] value of 1.0898563861846924 is not close enough to expected value of 1.0899707078933716
    run_depth_and_segmentation_test (oracle): Step 0 oracle failed: depth_map_list[0][339][376] value of 1.0898563861846924 is not close enough to expected value of 1.0899707078933716
```

this one was more frequent on test 171:
```
FAILED INTEGRATION TESTS:
    171.triggered_by_correct_sequence (oracle): Step 38 failed:
        objects chest_2 visible: True != False
```

Let me know if I'm missing something, thanks!

2023-05-15 15:29 UTC, jaudick commented
@phile-caci I spent a long time trying to resolve this error too. It was really frustrating because i couldn't replicate it consistently. I made a few fixes on performer position changes and was able to fix it for the few runs I tested after. Seems like you got it back though which is super frustrating because its not really a code issue. Functionally everything is fine. This is from my comment above
> this happened on the two frames where the middle chest was way off on the edge with a few visible pixels

@ThomasSchellenbergNextCentury @phile-caci How would you feel about me removing the visible check on steps 37- 39? I know its not the best practice but with only being a small pixel issue way off to the side frame I think its worth considering since this only happens when running the whole suite

2023-05-15 16:02 UTC, ThomasSchellenbergNextCentury commented
@jaudick Yeah that seems fine.

2023-05-16 14:09 UTC, jaudick commented
@phile-caci I pushed a fix for that test

2023-05-16 16:28 UTC, phile-caci reviewed
Hey @jaudick , are you seeing these too?

For Test 171,

```
    171.triggered_by_correct_sequence (oracle): Step 48 failed:
        objects chest_3 visible: False != True
        objects placer_1 visible: True != False
```
I changed them locally, and it looks like I'm not getting any more failures for 171

2023-05-16 18:28 UTC, jaudick commented
@phile-caci Sorry I found your message a little confusing. Are you still getting that new error then?

2023-05-16 18:30 UTC, phile-caci commented
> 171.triggered_by_correct_sequence (oracle): Step 48 failed:
>         objects chest_3 visible: False != True



> @phile-caci Sorry I found your message a little confusing. Are you still getting that new error then?

@jaudick , Sry, I was confusing myself too... I'm seeing this now:
```
    171.triggered_by_correct_sequence (oracle): Step 48 failed:
        objects chest_3 visible: False != True
```
Are you not seeing this?

2023-05-16 18:37 UTC, jaudick commented
@phile-caci No I dont think I have ever seen that one. Would you feel ok with me just getting rid of that check on that step. The important thing is that the ball drops down after the correct order.

2023-05-16 18:40 UTC, phile-caci commented
> @phile-caci No I dont think I have ever seen that one. Would you feel ok with me just getting rid of that check on that step. The important thing is that the ball drops down after the correct order.

I'm ok with it! (since that's what we did before)

2023-05-16 19:33 UTC, jaudick commented
@phile-caci Pushed a fix

2023-05-16 20:26 UTC, phile-caci approved these changes
Thanks @jaudick ,

Not seeing anymore errors in integration.

2023-05-17 01:25 UTC, ThomasSchellenbergNextCentury approved these changes
Tests pass. Re-approving.

2023-05-17 01:25 UTC, merged